// Auto-generated. Do not edit!

// (in-package ip_msgs.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class buoyFeedback {
  constructor() {
    this.errorx = 0;
    this.errory = 0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type buoyFeedback
    // Serialize message field [errorx]
    bufferInfo = _serializer.int32(obj.errorx, bufferInfo);
    // Serialize message field [errory]
    bufferInfo = _serializer.int32(obj.errory, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type buoyFeedback
    let tmp;
    let len;
    let data = new buoyFeedback();
    // Deserialize message field [errorx]
    tmp = _deserializer.int32(buffer);
    data.errorx = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [errory]
    tmp = _deserializer.int32(buffer);
    data.errory = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'ip_msgs/buoyFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'aada95332723c51ba6b85286d94eda17';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    int32 errorx
    int32 errory
    
    
    `;
  }

};

module.exports = buoyFeedback;
