// Generated by gencpp from file kraken_msgs/advancedControllerFeedback.msg
// DO NOT EDIT!


#ifndef KRAKEN_MSGS_MESSAGE_ADVANCEDCONTROLLERFEEDBACK_H
#define KRAKEN_MSGS_MESSAGE_ADVANCEDCONTROLLERFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kraken_msgs
{
template <class ContainerAllocator>
struct advancedControllerFeedback_
{
  typedef advancedControllerFeedback_<ContainerAllocator> Type;

  advancedControllerFeedback_()
    : running_time(0.0)  {
    }
  advancedControllerFeedback_(const ContainerAllocator& _alloc)
    : running_time(0.0)  {
  (void)_alloc;
    }



   typedef float _running_time_type;
  _running_time_type running_time;




  typedef boost::shared_ptr< ::kraken_msgs::advancedControllerFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kraken_msgs::advancedControllerFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct advancedControllerFeedback_

typedef ::kraken_msgs::advancedControllerFeedback_<std::allocator<void> > advancedControllerFeedback;

typedef boost::shared_ptr< ::kraken_msgs::advancedControllerFeedback > advancedControllerFeedbackPtr;
typedef boost::shared_ptr< ::kraken_msgs::advancedControllerFeedback const> advancedControllerFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kraken_msgs::advancedControllerFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kraken_msgs::advancedControllerFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kraken_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'kraken_msgs': ['/home/dyutimoy/catkin_ws/devel/share/kraken_msgs/msg', '/home/dyutimoy/catkin_ws/src/kraken_3.0/msgs_stack/kraken_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kraken_msgs::advancedControllerFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kraken_msgs::advancedControllerFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kraken_msgs::advancedControllerFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kraken_msgs::advancedControllerFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kraken_msgs::advancedControllerFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kraken_msgs::advancedControllerFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kraken_msgs::advancedControllerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2e4e5e2851a3713c120e74e45f192c2";
  }

  static const char* value(const ::kraken_msgs::advancedControllerFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2e4e5e2851a3713ULL;
  static const uint64_t static_value2 = 0xc120e74e45f192c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::kraken_msgs::advancedControllerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kraken_msgs/advancedControllerFeedback";
  }

  static const char* value(const ::kraken_msgs::advancedControllerFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kraken_msgs::advancedControllerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
float32 running_time\n\
\n\
";
  }

  static const char* value(const ::kraken_msgs::advancedControllerFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kraken_msgs::advancedControllerFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.running_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct advancedControllerFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kraken_msgs::advancedControllerFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kraken_msgs::advancedControllerFeedback_<ContainerAllocator>& v)
  {
    s << indent << "running_time: ";
    Printer<float>::stream(s, indent + "  ", v.running_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRAKEN_MSGS_MESSAGE_ADVANCEDCONTROLLERFEEDBACK_H
