// Generated by gencpp from file kraken_msgs/advancedControllerResult.msg
// DO NOT EDIT!


#ifndef KRAKEN_MSGS_MESSAGE_ADVANCEDCONTROLLERRESULT_H
#define KRAKEN_MSGS_MESSAGE_ADVANCEDCONTROLLERRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kraken_msgs
{
template <class ContainerAllocator>
struct advancedControllerResult_
{
  typedef advancedControllerResult_<ContainerAllocator> Type;

  advancedControllerResult_()
    : time_taken(0.0)  {
    }
  advancedControllerResult_(const ContainerAllocator& _alloc)
    : time_taken(0.0)  {
  (void)_alloc;
    }



   typedef float _time_taken_type;
  _time_taken_type time_taken;




  typedef boost::shared_ptr< ::kraken_msgs::advancedControllerResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kraken_msgs::advancedControllerResult_<ContainerAllocator> const> ConstPtr;

}; // struct advancedControllerResult_

typedef ::kraken_msgs::advancedControllerResult_<std::allocator<void> > advancedControllerResult;

typedef boost::shared_ptr< ::kraken_msgs::advancedControllerResult > advancedControllerResultPtr;
typedef boost::shared_ptr< ::kraken_msgs::advancedControllerResult const> advancedControllerResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kraken_msgs::advancedControllerResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kraken_msgs::advancedControllerResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kraken_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'kraken_msgs': ['/home/dyutimoy/catkin_ws/devel/share/kraken_msgs/msg', '/home/dyutimoy/catkin_ws/src/kraken_3.0/msgs_stack/kraken_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kraken_msgs::advancedControllerResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kraken_msgs::advancedControllerResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kraken_msgs::advancedControllerResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kraken_msgs::advancedControllerResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kraken_msgs::advancedControllerResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kraken_msgs::advancedControllerResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kraken_msgs::advancedControllerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb94241e261749226844ca094b5ee0a2";
  }

  static const char* value(const ::kraken_msgs::advancedControllerResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb94241e26174922ULL;
  static const uint64_t static_value2 = 0x6844ca094b5ee0a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::kraken_msgs::advancedControllerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kraken_msgs/advancedControllerResult";
  }

  static const char* value(const ::kraken_msgs::advancedControllerResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kraken_msgs::advancedControllerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result\n\
float32 time_taken\n\
\n\
";
  }

  static const char* value(const ::kraken_msgs::advancedControllerResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kraken_msgs::advancedControllerResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_taken);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct advancedControllerResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kraken_msgs::advancedControllerResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kraken_msgs::advancedControllerResult_<ContainerAllocator>& v)
  {
    s << indent << "time_taken: ";
    Printer<float>::stream(s, indent + "  ", v.time_taken);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRAKEN_MSGS_MESSAGE_ADVANCEDCONTROLLERRESULT_H
