// Generated by gencpp from file kraken_msgs/battery.msg
// DO NOT EDIT!


#ifndef KRAKEN_MSGS_MESSAGE_BATTERY_H
#define KRAKEN_MSGS_MESSAGE_BATTERY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kraken_msgs
{
template <class ContainerAllocator>
struct battery_
{
  typedef battery_<ContainerAllocator> Type;

  battery_()
    : header()
    , cell1(0.0)
    , cell2(0.0)
    , cell3(0.0)
    , cell4(0.0)
    , cell5(0.0)
    , cell6(0.0)
    , vcc(0.0)
    , current(0.0)
    , energy_consumed(0.0)
    , percent_left(0.0)  {
    }
  battery_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cell1(0.0)
    , cell2(0.0)
    , cell3(0.0)
    , cell4(0.0)
    , cell5(0.0)
    , cell6(0.0)
    , vcc(0.0)
    , current(0.0)
    , energy_consumed(0.0)
    , percent_left(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _cell1_type;
  _cell1_type cell1;

   typedef float _cell2_type;
  _cell2_type cell2;

   typedef float _cell3_type;
  _cell3_type cell3;

   typedef float _cell4_type;
  _cell4_type cell4;

   typedef float _cell5_type;
  _cell5_type cell5;

   typedef float _cell6_type;
  _cell6_type cell6;

   typedef float _vcc_type;
  _vcc_type vcc;

   typedef float _current_type;
  _current_type current;

   typedef float _energy_consumed_type;
  _energy_consumed_type energy_consumed;

   typedef float _percent_left_type;
  _percent_left_type percent_left;




  typedef boost::shared_ptr< ::kraken_msgs::battery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kraken_msgs::battery_<ContainerAllocator> const> ConstPtr;

}; // struct battery_

typedef ::kraken_msgs::battery_<std::allocator<void> > battery;

typedef boost::shared_ptr< ::kraken_msgs::battery > batteryPtr;
typedef boost::shared_ptr< ::kraken_msgs::battery const> batteryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kraken_msgs::battery_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kraken_msgs::battery_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kraken_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'kraken_msgs': ['/home/dyutimoy/catkin_ws/devel/share/kraken_msgs/msg', '/home/dyutimoy/catkin_ws/src/kraken_3.0/msgs_stack/kraken_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kraken_msgs::battery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kraken_msgs::battery_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kraken_msgs::battery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kraken_msgs::battery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kraken_msgs::battery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kraken_msgs::battery_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kraken_msgs::battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d535a09473d27f72b71883685e5447bb";
  }

  static const char* value(const ::kraken_msgs::battery_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd535a09473d27f72ULL;
  static const uint64_t static_value2 = 0xb71883685e5447bbULL;
};

template<class ContainerAllocator>
struct DataType< ::kraken_msgs::battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kraken_msgs/battery";
  }

  static const char* value(const ::kraken_msgs::battery_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kraken_msgs::battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 cell1\n\
float32 cell2\n\
float32 cell3\n\
float32 cell4\n\
float32 cell5\n\
float32 cell6\n\
float32 vcc\n\
float32 current\n\
float32 energy_consumed\n\
float32 percent_left\n\
 \n\
\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::kraken_msgs::battery_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kraken_msgs::battery_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cell1);
      stream.next(m.cell2);
      stream.next(m.cell3);
      stream.next(m.cell4);
      stream.next(m.cell5);
      stream.next(m.cell6);
      stream.next(m.vcc);
      stream.next(m.current);
      stream.next(m.energy_consumed);
      stream.next(m.percent_left);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct battery_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kraken_msgs::battery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kraken_msgs::battery_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cell1: ";
    Printer<float>::stream(s, indent + "  ", v.cell1);
    s << indent << "cell2: ";
    Printer<float>::stream(s, indent + "  ", v.cell2);
    s << indent << "cell3: ";
    Printer<float>::stream(s, indent + "  ", v.cell3);
    s << indent << "cell4: ";
    Printer<float>::stream(s, indent + "  ", v.cell4);
    s << indent << "cell5: ";
    Printer<float>::stream(s, indent + "  ", v.cell5);
    s << indent << "cell6: ";
    Printer<float>::stream(s, indent + "  ", v.cell6);
    s << indent << "vcc: ";
    Printer<float>::stream(s, indent + "  ", v.vcc);
    s << indent << "current: ";
    Printer<float>::stream(s, indent + "  ", v.current);
    s << indent << "energy_consumed: ";
    Printer<float>::stream(s, indent + "  ", v.energy_consumed);
    s << indent << "percent_left: ";
    Printer<float>::stream(s, indent + "  ", v.percent_left);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRAKEN_MSGS_MESSAGE_BATTERY_H
