// Generated by gencpp from file kraken_msgs/controllerGoal.msg
// DO NOT EDIT!


#ifndef KRAKEN_MSGS_MESSAGE_CONTROLLERGOAL_H
#define KRAKEN_MSGS_MESSAGE_CONTROLLERGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kraken_msgs
{
template <class ContainerAllocator>
struct controllerGoal_
{
  typedef controllerGoal_<ContainerAllocator> Type;

  controllerGoal_()
    : r(0.0)
    , p(0.0)
    , y(0.0)
    , d(0.0)  {
    }
  controllerGoal_(const ContainerAllocator& _alloc)
    : r(0.0)
    , p(0.0)
    , y(0.0)
    , d(0.0)  {
  (void)_alloc;
    }



   typedef float _r_type;
  _r_type r;

   typedef float _p_type;
  _p_type p;

   typedef float _y_type;
  _y_type y;

   typedef float _d_type;
  _d_type d;




  typedef boost::shared_ptr< ::kraken_msgs::controllerGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kraken_msgs::controllerGoal_<ContainerAllocator> const> ConstPtr;

}; // struct controllerGoal_

typedef ::kraken_msgs::controllerGoal_<std::allocator<void> > controllerGoal;

typedef boost::shared_ptr< ::kraken_msgs::controllerGoal > controllerGoalPtr;
typedef boost::shared_ptr< ::kraken_msgs::controllerGoal const> controllerGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kraken_msgs::controllerGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kraken_msgs::controllerGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kraken_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'kraken_msgs': ['/home/dyutimoy/catkin_ws/devel/share/kraken_msgs/msg', '/home/dyutimoy/catkin_ws/src/kraken_3.0/msgs_stack/kraken_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kraken_msgs::controllerGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kraken_msgs::controllerGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kraken_msgs::controllerGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kraken_msgs::controllerGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kraken_msgs::controllerGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kraken_msgs::controllerGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kraken_msgs::controllerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "210de68057aa57422cc623208f76e5d6";
  }

  static const char* value(const ::kraken_msgs::controllerGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x210de68057aa5742ULL;
  static const uint64_t static_value2 = 0x2cc623208f76e5d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::kraken_msgs::controllerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kraken_msgs/controllerGoal";
  }

  static const char* value(const ::kraken_msgs::controllerGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kraken_msgs::controllerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal\n\
float32 r\n\
float32 p\n\
float32 y\n\
float32 d\n\
\n\
";
  }

  static const char* value(const ::kraken_msgs::controllerGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kraken_msgs::controllerGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.r);
      stream.next(m.p);
      stream.next(m.y);
      stream.next(m.d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct controllerGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kraken_msgs::controllerGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kraken_msgs::controllerGoal_<ContainerAllocator>& v)
  {
    s << indent << "r: ";
    Printer<float>::stream(s, indent + "  ", v.r);
    s << indent << "p: ";
    Printer<float>::stream(s, indent + "  ", v.p);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "d: ";
    Printer<float>::stream(s, indent + "  ", v.d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRAKEN_MSGS_MESSAGE_CONTROLLERGOAL_H
