// Auto-generated. Do not edit!

// (in-package kraken_msgs.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class advancedControllerGoal {
  constructor() {
    this.flag = 0;
    this.x = 0.0;
    this.y = 0.0;
    this.depth = 0.0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type advancedControllerGoal
    // Serialize message field [flag]
    bufferInfo = _serializer.int32(obj.flag, bufferInfo);
    // Serialize message field [x]
    bufferInfo = _serializer.float32(obj.x, bufferInfo);
    // Serialize message field [y]
    bufferInfo = _serializer.float32(obj.y, bufferInfo);
    // Serialize message field [depth]
    bufferInfo = _serializer.float32(obj.depth, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type advancedControllerGoal
    let tmp;
    let len;
    let data = new advancedControllerGoal();
    // Deserialize message field [flag]
    tmp = _deserializer.int32(buffer);
    data.flag = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [x]
    tmp = _deserializer.float32(buffer);
    data.x = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [y]
    tmp = _deserializer.float32(buffer);
    data.y = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [depth]
    tmp = _deserializer.float32(buffer);
    data.depth = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'kraken_msgs/advancedControllerGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '757d1c6f47df020d70637830ba957a9d';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal
    int32 flag ##flag==0 means global destination and flag==1 means local destination
    float32 x
    float32 y
    float32 depth
    
    
    `;
  }

};

module.exports = advancedControllerGoal;
