// Auto-generated. Do not edit!

// (in-package kraken_msgs.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class controllerResult {
  constructor() {
    this.time_taken = 0.0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type controllerResult
    // Serialize message field [time_taken]
    bufferInfo = _serializer.float32(obj.time_taken, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type controllerResult
    let tmp;
    let len;
    let data = new controllerResult();
    // Deserialize message field [time_taken]
    tmp = _deserializer.float32(buffer);
    data.time_taken = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'kraken_msgs/controllerResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'bb94241e261749226844ca094b5ee0a2';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result
    float32 time_taken
    
    
    `;
  }

};

module.exports = controllerResult;
