// Auto-generated. Do not edit!

// (in-package kraken_msgs.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class controllerFeedback {
  constructor() {
    this.running_time = 0.0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type controllerFeedback
    // Serialize message field [running_time]
    bufferInfo = _serializer.float32(obj.running_time, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type controllerFeedback
    let tmp;
    let len;
    let data = new controllerFeedback();
    // Deserialize message field [running_time]
    tmp = _deserializer.float32(buffer);
    data.running_time = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'kraken_msgs/controllerFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'c2e4e5e2851a3713c120e74e45f192c2';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    float32 running_time
    
    `;
  }

};

module.exports = controllerFeedback;
