// Auto-generated. Do not edit!

// (in-package kraken_msgs.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class controllerGoal {
  constructor() {
    this.r = 0.0;
    this.p = 0.0;
    this.y = 0.0;
    this.d = 0.0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type controllerGoal
    // Serialize message field [r]
    bufferInfo = _serializer.float32(obj.r, bufferInfo);
    // Serialize message field [p]
    bufferInfo = _serializer.float32(obj.p, bufferInfo);
    // Serialize message field [y]
    bufferInfo = _serializer.float32(obj.y, bufferInfo);
    // Serialize message field [d]
    bufferInfo = _serializer.float32(obj.d, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type controllerGoal
    let tmp;
    let len;
    let data = new controllerGoal();
    // Deserialize message field [r]
    tmp = _deserializer.float32(buffer);
    data.r = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [p]
    tmp = _deserializer.float32(buffer);
    data.p = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [y]
    tmp = _deserializer.float32(buffer);
    data.y = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [d]
    tmp = _deserializer.float32(buffer);
    data.d = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'kraken_msgs/controllerGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '210de68057aa57422cc623208f76e5d6';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal
    float32 r
    float32 p
    float32 y
    float32 d
    
    
    `;
  }

};

module.exports = controllerGoal;
