// Auto-generated. Do not edit!

// (in-package kraken_msgs.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class scanGoal {
  constructor() {
    this.direction = 0;
    this.speed = 0.0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type scanGoal
    // Serialize message field [direction]
    bufferInfo = _serializer.int32(obj.direction, bufferInfo);
    // Serialize message field [speed]
    bufferInfo = _serializer.float32(obj.speed, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type scanGoal
    let tmp;
    let len;
    let data = new scanGoal();
    // Deserialize message field [direction]
    tmp = _deserializer.int32(buffer);
    data.direction = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [speed]
    tmp = _deserializer.float32(buffer);
    data.speed = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'kraken_msgs/scanGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '0181899c23ee952a295cdd8e12ba54de';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal
    int32 direction		# +1 for Clockwise and -1 for Counter-clockwise
    float32 speed
    
    
    `;
  }

};

module.exports = scanGoal;
