// Auto-generated. Do not edit!

// (in-package kraken_msgs.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class setYawFeedback {
  constructor() {
    this.header = new std_msgs.msg.Header();
    this.Desired_yaw = 0.0;
    this.Current_yaw = 0.0;
    this.Error = 0.0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type setYawFeedback
    // Serialize message field [header]
    bufferInfo = std_msgs.msg.Header.serialize(obj.header, bufferInfo);
    // Serialize message field [Desired_yaw]
    bufferInfo = _serializer.float32(obj.Desired_yaw, bufferInfo);
    // Serialize message field [Current_yaw]
    bufferInfo = _serializer.float32(obj.Current_yaw, bufferInfo);
    // Serialize message field [Error]
    bufferInfo = _serializer.float32(obj.Error, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type setYawFeedback
    let tmp;
    let len;
    let data = new setYawFeedback();
    // Deserialize message field [header]
    tmp = std_msgs.msg.Header.deserialize(buffer);
    data.header = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [Desired_yaw]
    tmp = _deserializer.float32(buffer);
    data.Desired_yaw = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [Current_yaw]
    tmp = _deserializer.float32(buffer);
    data.Current_yaw = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [Error]
    tmp = _deserializer.float32(buffer);
    data.Error = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'kraken_msgs/setYawFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '7118c515219415471afc64514800b41f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # feedback
    Header header
    float32 Desired_yaw
    float32 Current_yaw
    float32 Error
    
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    `;
  }

};

module.exports = setYawFeedback;
