; Auto-generated. Do not edit!


(cl:in-package ip_msgs-msg)


;//! \htmlinclude buoyGoal.msg.html

(cl:defclass <buoyGoal> (roslisp-msg-protocol:ros-message)
  ((order
    :reader order
    :initarg :order
    :type cl:integer
    :initform 0))
)

(cl:defclass buoyGoal (<buoyGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <buoyGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'buoyGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ip_msgs-msg:<buoyGoal> is deprecated: use ip_msgs-msg:buoyGoal instead.")))

(cl:ensure-generic-function 'order-val :lambda-list '(m))
(cl:defmethod order-val ((m <buoyGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ip_msgs-msg:order-val is deprecated.  Use ip_msgs-msg:order instead.")
  (order m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <buoyGoal>) ostream)
  "Serializes a message object of type '<buoyGoal>"
  (cl:let* ((signed (cl:slot-value msg 'order)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <buoyGoal>) istream)
  "Deserializes a message object of type '<buoyGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'order) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<buoyGoal>)))
  "Returns string type for a message object of type '<buoyGoal>"
  "ip_msgs/buoyGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'buoyGoal)))
  "Returns string type for a message object of type 'buoyGoal"
  "ip_msgs/buoyGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<buoyGoal>)))
  "Returns md5sum for a message object of type '<buoyGoal>"
  "6889063349a00b249bd1661df429d822")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'buoyGoal)))
  "Returns md5sum for a message object of type 'buoyGoal"
  "6889063349a00b249bd1661df429d822")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<buoyGoal>)))
  "Returns full string definition for message of type '<buoyGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%int32 order~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'buoyGoal)))
  "Returns full string definition for message of type 'buoyGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%int32 order~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <buoyGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <buoyGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'buoyGoal
    (cl:cons ':order (order msg))
))
