; Auto-generated. Do not edit!


(cl:in-package ip_msgs-msg)


;//! \htmlinclude buoyFeedback.msg.html

(cl:defclass <buoyFeedback> (roslisp-msg-protocol:ros-message)
  ((errorx
    :reader errorx
    :initarg :errorx
    :type cl:integer
    :initform 0)
   (errory
    :reader errory
    :initarg :errory
    :type cl:integer
    :initform 0))
)

(cl:defclass buoyFeedback (<buoyFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <buoyFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'buoyFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ip_msgs-msg:<buoyFeedback> is deprecated: use ip_msgs-msg:buoyFeedback instead.")))

(cl:ensure-generic-function 'errorx-val :lambda-list '(m))
(cl:defmethod errorx-val ((m <buoyFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ip_msgs-msg:errorx-val is deprecated.  Use ip_msgs-msg:errorx instead.")
  (errorx m))

(cl:ensure-generic-function 'errory-val :lambda-list '(m))
(cl:defmethod errory-val ((m <buoyFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ip_msgs-msg:errory-val is deprecated.  Use ip_msgs-msg:errory instead.")
  (errory m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <buoyFeedback>) ostream)
  "Serializes a message object of type '<buoyFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'errorx)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (cl:let* ((signed (cl:slot-value msg 'errory)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <buoyFeedback>) istream)
  "Deserializes a message object of type '<buoyFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'errorx) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'errory) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<buoyFeedback>)))
  "Returns string type for a message object of type '<buoyFeedback>"
  "ip_msgs/buoyFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'buoyFeedback)))
  "Returns string type for a message object of type 'buoyFeedback"
  "ip_msgs/buoyFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<buoyFeedback>)))
  "Returns md5sum for a message object of type '<buoyFeedback>"
  "aada95332723c51ba6b85286d94eda17")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'buoyFeedback)))
  "Returns md5sum for a message object of type 'buoyFeedback"
  "aada95332723c51ba6b85286d94eda17")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<buoyFeedback>)))
  "Returns full string definition for message of type '<buoyFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 errorx~%int32 errory~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'buoyFeedback)))
  "Returns full string definition for message of type 'buoyFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 errorx~%int32 errory~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <buoyFeedback>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <buoyFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'buoyFeedback
    (cl:cons ':errorx (errorx msg))
    (cl:cons ':errory (errory msg))
))
