; Auto-generated. Do not edit!


(cl:in-package ip_msgs-msg)


;//! \htmlinclude vgateGoal.msg.html

(cl:defclass <vgateGoal> (roslisp-msg-protocol:ros-message)
  ((order
    :reader order
    :initarg :order
    :type cl:integer
    :initform 0))
)

(cl:defclass vgateGoal (<vgateGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <vgateGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'vgateGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ip_msgs-msg:<vgateGoal> is deprecated: use ip_msgs-msg:vgateGoal instead.")))

(cl:ensure-generic-function 'order-val :lambda-list '(m))
(cl:defmethod order-val ((m <vgateGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ip_msgs-msg:order-val is deprecated.  Use ip_msgs-msg:order instead.")
  (order m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <vgateGoal>) ostream)
  "Serializes a message object of type '<vgateGoal>"
  (cl:let* ((signed (cl:slot-value msg 'order)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <vgateGoal>) istream)
  "Deserializes a message object of type '<vgateGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'order) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<vgateGoal>)))
  "Returns string type for a message object of type '<vgateGoal>"
  "ip_msgs/vgateGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'vgateGoal)))
  "Returns string type for a message object of type 'vgateGoal"
  "ip_msgs/vgateGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<vgateGoal>)))
  "Returns md5sum for a message object of type '<vgateGoal>"
  "6889063349a00b249bd1661df429d822")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'vgateGoal)))
  "Returns md5sum for a message object of type 'vgateGoal"
  "6889063349a00b249bd1661df429d822")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<vgateGoal>)))
  "Returns full string definition for message of type '<vgateGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 order~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'vgateGoal)))
  "Returns full string definition for message of type 'vgateGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 order~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <vgateGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <vgateGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'vgateGoal
    (cl:cons ':order (order msg))
))
