; Auto-generated. Do not edit!


(cl:in-package ip_msgs-msg)


;//! \htmlinclude vgateFeedback.msg.html

(cl:defclass <vgateFeedback> (roslisp-msg-protocol:ros-message)
  ((errorx
    :reader errorx
    :initarg :errorx
    :type cl:integer
    :initform 0)
   (errory
    :reader errory
    :initarg :errory
    :type cl:float
    :initform 0.0))
)

(cl:defclass vgateFeedback (<vgateFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <vgateFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'vgateFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ip_msgs-msg:<vgateFeedback> is deprecated: use ip_msgs-msg:vgateFeedback instead.")))

(cl:ensure-generic-function 'errorx-val :lambda-list '(m))
(cl:defmethod errorx-val ((m <vgateFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ip_msgs-msg:errorx-val is deprecated.  Use ip_msgs-msg:errorx instead.")
  (errorx m))

(cl:ensure-generic-function 'errory-val :lambda-list '(m))
(cl:defmethod errory-val ((m <vgateFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ip_msgs-msg:errory-val is deprecated.  Use ip_msgs-msg:errory instead.")
  (errory m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <vgateFeedback>) ostream)
  "Serializes a message object of type '<vgateFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'errorx)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'errory))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <vgateFeedback>) istream)
  "Deserializes a message object of type '<vgateFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'errorx) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'errory) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<vgateFeedback>)))
  "Returns string type for a message object of type '<vgateFeedback>"
  "ip_msgs/vgateFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'vgateFeedback)))
  "Returns string type for a message object of type 'vgateFeedback"
  "ip_msgs/vgateFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<vgateFeedback>)))
  "Returns md5sum for a message object of type '<vgateFeedback>"
  "45c0637c31dcffaf124c057eba6c9894")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'vgateFeedback)))
  "Returns md5sum for a message object of type 'vgateFeedback"
  "45c0637c31dcffaf124c057eba6c9894")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<vgateFeedback>)))
  "Returns full string definition for message of type '<vgateFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 errorx~%float32 errory~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'vgateFeedback)))
  "Returns full string definition for message of type 'vgateFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 errorx~%float32 errory~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <vgateFeedback>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <vgateFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'vgateFeedback
    (cl:cons ':errorx (errorx msg))
    (cl:cons ':errory (errory msg))
))
